/**
 * Created by Dedrick Kitamuka on 04/04/2017.
 */

/**
 * The service is used to contain logic which will be shared across
 * many angular component (controller, service, directive, filter, component)
 *
 * AngularJS services are:
 * Lazily instantiated – AngularJS only instantiates a service when an application component depends on it.
 * Singletons – Each component dependent on a service gets a reference to the single instance generated by the service factory.
 **/

var serviceModule = angular.module('myServiceModule', []);

serviceModule.factory('notify', ['$window', function(win) {
  var tokens = [];
  return function(tkn) {
    tokens.push(tkn);
    if (tokens.length === 3) {
      win.alert(tokens.join('\n'));
      tokens = [];
    }
  };
}]);

